### ISSUE TITLE
django 2 compatibility

### ISSUE THREAD

**Issue by just1602** [caravancoop/rest-framework-auth-toolkit#28]
It'd be cool to check if ti's completly compatible with django 2 and if so, bump the package dependency.

**Comment by merwok** [comment]
Plan:

- remove explicit dependency on django and drf, it should be the app's responsibility to manage that
- move facepy to an extra require
- rework tox and CI config to test django 1.11 and 2.0

**Comment by merwok** [comment]
«rework tox» doesn’t apply given that we have no tests at the moment :smile: 

Plan for later:
- write unit tests
- make tox config to run unit tests with django 1.11, 2.0 and 2.1
- in the demo app, have two sets of requirements files + urls1.py/urls2.py to be compatible with django 1.11 and vs 2.x
- functional tests can use both variants of the demo app

**Comment by merwok** [comment]
Let’s consider this fixed.
